export const FILTER_CATEGORY = {
  tab: ['track', 'course'],
  type: ['Course', 'Sequential'],
  category: [
    'Programming Basics',
    'Data Science',
    'Web Development',
    'AI',
    'Algorithms',
  ],
  level: [
    'Introductory',
    'Beginner',
    'Intermediate',
    'Advanced',
    'Superlative',
  ],
  language: [
    'C',
    'C++',
    'Java',
    'Python',
    'JavaScript',
    'R',
    'HTML/CSS',
    'SQL',
    'Arduino',
    'Scratch',
    'Kotlin',
    'Swift',
    'Entry',
  ],
  price: ['Free', 'Payment', 'Subscription', 'Unit'],
};
